[model]
appliances = [ "fridge", "dish_washer", "washing_machine",]
train_size = 0.8
valid_size = 0.1
period = "1min"
input_len = 510
border = 15
max_power = 10000.0
power_scale = 2000.0
name = "ConvModel"
batch_size = 32
epochs = 100
patience = 30
init_features = 32
learning_rate = 0.0001
dropout = 0.1
regression_w = 1.0
classification_w = 0.0
num_models = 5

[plot]
f1_lim = [ 0.4, 1.0,]
nde_lim = [ 0.3, 0.8,]
figsize = [ 4, 3,]
num_plots = 10

[model.threshold]
method = "at"
num_status = 2

[model.buildings]
ukdale = [ 1, 2, 5,]

[plot.appliances]
dish_washer = "Dishwasher"
fridge = "Fridge"
washing_machine = "Washing machine"

[plot.thresh_color]
at = "b"
mp = "g"
vs = "r"

[at_2.dish_washer]
thresholds = [ 0.0, 10.0,]
centroids = [ 0.0, 10.0,]

[at_2.fridge]
thresholds = [ 0.0, 50.0,]
centroids = [ 0.0, 50.0,]

[at_2.washing_machine]
thresholds = [ 0.0, 20.0,]
centroids = [ 0.0, 20.0,]

[model.dates.ukdale]
1 = [ "2013-04-12", "2014-09-15",]
2 = [ "2013-05-22", "2013-10-03 6:16",]
5 = [ "2014-04-29", "2014-09-01",]

[model.buildings.train]
ukdale = [ 1, 2, 5,]

[model.buildings.validation]
ukdale = [ 1,]

[model.buildings.test]
ukdale = [ 1,]
